In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [31]:
df = pd.read_csv('/content/credit_card_fraud_2026.csv')

In [32]:
df.head()

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0


In [33]:
df.shape

(20000, 26)

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.isna().sum()

,0
transaction_id,0
amount_usd,0
merchant_category,0
card_type,0
auth_method,0
channel,0
device_type,0
is_foreign_transaction,0
hours_since_last_txn,0
txn_count_last_24h,0


In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   transaction_id                20000 non-null  int64  
 1   amount_usd                    20000 non-null  float64
 2   merchant_category             20000 non-null  object 
 3   card_type                     20000 non-null  object 
 4   auth_method                   20000 non-null  object 
 5   channel                       20000 non-null  object 
 6   device_type                   20000 non-null  object 
 7   is_foreign_transaction        20000 non-null  bool   
 8   hours_since_last_txn          20000 non-null  float64
 9   txn_count_last_24h            20000 non-null  int64  
 10  distance_from_home_km         20000 non-null  float64
 11  card_age_months               20000 non-null  int64  
 12  customer_age                  20000 non-null  int64  
 13  a

In [37]:
df.dtypes

,0
transaction_id,int64
amount_usd,float64
merchant_category,object
card_type,object
auth_method,object
channel,object
device_type,object
is_foreign_transaction,bool
hours_since_last_txn,float64
txn_count_last_24h,int64


In [38]:
df['transaction_id'].value_counts()

,count
transaction_id,
19984,1
19983,1
19982,1
19981,1
19980,1
...,...
5,1
4,1
3,1


In [39]:
df['transaction_id'].nunique()

20000

In [40]:
df['transaction_id'].nunique() == len(df)

True

In [41]:
df.drop(columns=['transaction_id'], inplace=True)

In [42]:
df['merchant_category'].value_counts()

,count
merchant_category,
Online Retail,3416
Groceries,3242
Restaurants,2534
Electronics,2032
Fuel,1565
Travel,1420
Utilities,1330
Healthcare,1237
Gaming,1036


In [43]:
df['merchant_category'].nunique()

12

In [44]:
df['card_type'].value_counts()

,count
card_type,
Visa,8417
Mastercard,6629
Amex,2135
RuPay,1796
Discover,1023


In [45]:
df['card_type'].nunique()

5

In [46]:
df['auth_method'].value_counts()

,count
auth_method,
3D Secure,5554
OTP,4792
PIN,4173
Biometric,3093
No Authentication,2388


In [47]:
df['auth_method'].nunique()

5

In [48]:
df['channel'].value_counts()

,count
channel,
Online,6810
POS,5191
Contactless,3400
In-App,3225
ATM,1374


In [49]:
df['channel'].nunique()

5

In [50]:
df['device_type'].value_counts()

,count
device_type,
Android Phone,5503
iPhone,4179
POS Terminal,3162
Windows PC,2623
Mac,1359
Tablet,1161
Smart Watch,1008
ATM Machine,1005


In [51]:
df['hours_since_last_txn'].head()

,hours_since_last_txn
0,13.54
1,0.71
2,0.35
3,3.42
4,2.43


In [52]:
df['hours_since_last_txn'].unique()[:20]

array([13.54,  0.71,  0.35,  3.42,  2.43,  5.94, 18.31, 25.56,  6.28,
        0.78,  0.32,  5.78, 11.63,  5.98,  3.39,  3.72,  2.54,  1.48,
        0.68,  4.1 ])

In [53]:
df['hours_since_last_txn'].dtype

dtype('float64')

In [54]:
df['is_foreign_transaction'] = df['is_foreign_transaction'].astype('int64')
df['ip_country_mismatch'] = df['ip_country_mismatch'].astype('int64')
df['billing_shipping_mismatch'] = df['billing_shipping_mismatch'].astype('int64')
df['is_ai_generated_scam_attempt'] = df['is_ai_generated_scam_attempt'].astype('int64')
df['is_new_merchant'] = df['is_new_merchant'].astype('int64')
df['used_vpn'] = df['used_vpn'].astype('int64')

In [55]:
df = pd.get_dummies(df, columns=['merchant_category', 'card_type', 'auth_method', 'channel', 'device_type'], dtype='int64', drop_first=True)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 50 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   amount_usd                       20000 non-null  float64
 1   is_foreign_transaction           20000 non-null  int64  
 2   hours_since_last_txn             20000 non-null  float64
 3   txn_count_last_24h               20000 non-null  int64  
 4   distance_from_home_km            20000 non-null  float64
 5   card_age_months                  20000 non-null  int64  
 6   customer_age                     20000 non-null  int64  
 7   account_balance_usd              20000 non-null  float64
 8   is_new_merchant                  20000 non-null  int64  
 9   used_vpn                         20000 non-null  int64  
 10  ip_country_mismatch              20000 non-null  int64  
 11  billing_shipping_mismatch        20000 non-null  int64  
 12  cvv_retry_count   

In [57]:
print(df['is_fraud'].describe(),
      df['is_fraud'].skew())

count    20000.000000
mean         0.016950
std          0.129087
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: is_fraud, dtype: float64 7.484831038041035


In [58]:
df['is_fraud'].value_counts()

,count
is_fraud,
0,19661
1,339


In [59]:
X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [61]:
print(X_train.shape,
      X_test.shape,
      y_train.shape,
      y_test.shape)

(16000, 49) (4000, 49) (16000,) (4000,)


In [62]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [63]:
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

In [64]:
np.mean(X_train_scaled, axis=0)
np.std(X_train_scaled, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.mean(X_test_scaled, axis=0)
np.std(X_test_scaled, axis=0)

array([0.8467935 , 1.02809788, 1.0011504 , 0.99840046, 1.00254004,
       1.00170578, 1.02132992, 0.9440562 , 0.99703991, 1.0051305 ,
       0.9969813 , 0.97392327, 0.97542415, 0.99481817, 1.00009763,
       1.00190717, 1.0163163 , 1.00259562, 0.98686393, 0.96222555,
       1.03626628, 0.99657601, 0.99312822, 0.98244413, 1.04819571,
       1.01928441, 1.03563732, 0.86438492, 0.97753477, 1.01739901,
       0.99537218, 1.00028504, 0.98393881, 1.00096305, 0.97782918,
       1.03845561, 1.01044112, 0.97896668, 1.01235029, 1.00312638,
       0.9916008 , 0.9999218 , 0.99123602, 0.97255518, 0.9972675 ,
       1.03328629, 0.96131834, 1.00242565, 1.0164318 ])

In [104]:
from sklearn.linear_model import LogisticRegression

model_log = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    random_state=42
)

In [105]:
model_log.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [106]:
pred_log = model_log.predict(X_test_scaled)

In [107]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

print(confusion_matrix(y_test, pred_log))
print(classification_report(y_test, pred_log))

print("ROC-AUC:", roc_auc_score(y_test, pred_log))
print("PR-AUC:", average_precision_score(y_test, pred_log))

[[3475  457]
 [  13   55]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94      3932
           1       0.11      0.81      0.19        68

    accuracy                           0.88      4000
   macro avg       0.55      0.85      0.56      4000
weighted avg       0.98      0.88      0.92      4000

ROC-AUC: 0.8462988450721082
PR-AUC: 0.09013534007352941


In [108]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [109]:
model_log = Pipeline([
    ('scaler', StandardScaler()),
    ('log', LogisticRegression(
        max_iter=1000,
        class_weight='balanced',
        random_state=42
    ))
])


In [110]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(
    model_log,
    X,
    y,
    cv=5,
    scoring='accuracy'
)

print(score)
print("Mean Accuracy:", score.mean())

[0.88325 0.877   0.873   0.8815  0.879  ]
Mean Accuracy: 0.8787500000000001


In [111]:
scores = cross_val_score(
    model_log,
    X,
    y,
    cv=5,
    scoring='accuracy'
)

print(scores)
print("Mean Accuracy:", scores.mean())

[0.88325 0.877   0.873   0.8815  0.879  ]
Mean Accuracy: 0.8787500000000001


In [112]:
from sklearn.metrics import classification_report, confusion_matrix

pred_log = model_log.fit(X_train, y_train).predict(X_test)

print(confusion_matrix(y_test, pred_log))
print(classification_report(y_test, pred_log))

[[3475  457]
 [  13   55]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94      3932
           1       0.11      0.81      0.19        68

    accuracy                           0.88      4000
   macro avg       0.55      0.85      0.56      4000
weighted avg       0.98      0.88      0.92      4000



In [113]:
from sklearn.metrics import roc_auc_score

pred_proba = model_log.predict_proba(X_test)[:, 1]
print("ROC-AUC:", roc_auc_score(y_test, pred_proba))

ROC-AUC: 0.9344294177487883


In [114]:
# F1 Score
scores = cross_val_score(model_log, X, y, cv=5, scoring='f1')
print("Mean F1:", scores.mean())

# Recall (how many frauds are detected)
scores = cross_val_score(model_log, X, y, cv=5, scoring='recall')
print("Mean Recall:", scores.mean())

# Balanced Accuracy
scores = cross_val_score(model_log, X, y, cv=5, scoring='balanced_accuracy')
print("Mean Balanced Accuracy:", scores.mean())

Mean F1: 0.19037367599319754
Mean Recall: 0.840649692712906
Mean Balanced Accuracy: 0.8600276868389086


In [115]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    n_estimators=300,
    class_weight='balanced',
    max_depth=10,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

In [116]:
model_rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_leaf=2, n_estimators=300, n_jobs=-1,
                       random_state=42)

In [117]:
pred_rf = model_rf.predict(X_test)
pred_proba_rf = model_rf.predict_proba(X_test)[:, 1]

In [118]:
print(confusion_matrix(y_test, pred_rf))
print(classification_report(
    y_test,
    pred_rf,
    zero_division=0
))

[[3911   21]
 [  60    8]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      3932
           1       0.28      0.12      0.16        68

    accuracy                           0.98      4000
   macro avg       0.63      0.56      0.58      4000
weighted avg       0.97      0.98      0.98      4000



In [119]:
print("ROC-AUC:", roc_auc_score(y_test, pred_proba_rf))

ROC-AUC: 0.9108820537370594


In [120]:
scores = cross_val_score(
    model_rf,
    X,
    y,
    cv=5,
    scoring='f1'
)

print(scores)
print("Mean F1:", scores.mean())

[0.08       0.18181818 0.14814815 0.1980198  0.29357798]
Mean F1: 0.18031282271958085


In [121]:
# F1 Score
scores = cross_val_score(model_rf, X, y, cv=5, scoring='f1')
print("Mean F1:", scores.mean())

# Recall (how many frauds are detected)
scores = cross_val_score(model_rf, X, y, cv=5, scoring='recall')
print("Mean Recall:", scores.mean())

# Balanced Accuracy
scores = cross_val_score(model_rf, X, y, cv=5, scoring='balanced_accuracy')
print("Mean Balanced Accuracy:", scores.mean())

Mean F1: 0.18031282271958085
Mean Recall: 0.13841088674275678
Mean Balanced Accuracy: 0.5658739930536325


In [122]:
print(pred_proba_rf.min())
print(pred_proba_rf.max())
print(pred_proba_rf.mean())

0.009043020086366194
0.7569427811894467
0.12150107195972902


In [123]:
from xgboost import XGBClassifier

model_xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

In [124]:
model_xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, ...)

In [125]:
pred_xgb = model_xgb.predict(X_test)
pred_proba_xgb = model_xgb.predict_proba(X_test)[:, 1]

In [126]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print(confusion_matrix(y_test, pred_xgb))
print(classification_report(
    y_test,
    pred_xgb,
    zero_division=0
))

print("ROC-AUC:", roc_auc_score(y_test, pred_proba_xgb))

[[3929    3]
 [  62    6]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3932
           1       0.67      0.09      0.16        68

    accuracy                           0.98      4000
   macro avg       0.83      0.54      0.57      4000
weighted avg       0.98      0.98      0.98      4000

ROC-AUC: 0.9189493447429837


In [127]:
print("ROC-AUC:", roc_auc_score(y_test, pred_proba_xgb))

ROC-AUC: 0.9189493447429837


In [128]:
scores = cross_val_score(
    model_xgb,
    X,
    y,
    cv=5,
    scoring='f1'
)

print(scores)
print("Mean F1:", scores.mean())

[0.17948718 0.10666667 0.12987013 0.15       0.15384615]
Mean F1: 0.14397402597402598


In [129]:
# F1 Score
scores = cross_val_score(model_xgb, X, y, cv=5, scoring='f1')
print("Mean F1:", scores.mean())

# Recall (how many frauds are detected)
scores = cross_val_score(model_xgb, X, y, cv=5, scoring='recall')
print("Mean Recall:", scores.mean())

# Balanced Accuracy
scores = cross_val_score(model_xgb, X, y, cv=5, scoring='balanced_accuracy')
print("Mean Balanced Accuracy:", scores.mean())

Mean F1: 0.14397402597402598
Mean Recall: 0.08266022827041265
Mean Balanced Accuracy: 0.5407960606518731


In [130]:
from sklearn.ensemble import GradientBoostingClassifier

model_gbr = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

In [131]:
model_gbr.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200,
                           random_state=42)

In [132]:
pred_gbr = model_gbr.predict(X_test)
pred_proba_gbr = model_gbr.predict_proba(X_test)[:, 1]

In [133]:
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print(confusion_matrix(y_test, pred_gbr))
print(classification_report(
    y_test,
    pred_gbr,
    zero_division=0
))

print("ROC-AUC:", roc_auc_score(y_test, pred_proba_gbr))

[[3925    7]
 [  58   10]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      3932
           1       0.59      0.15      0.24        68

    accuracy                           0.98      4000
   macro avg       0.79      0.57      0.61      4000
weighted avg       0.98      0.98      0.98      4000

ROC-AUC: 0.9234336664472503


In [134]:
print("ROC-AUC:", roc_auc_score(y_test, pred_proba_gbr))

ROC-AUC: 0.9234336664472503


In [135]:
scores = cross_val_score(
    model_gbr,
    X,
    y,
    cv=5,
    scoring='f1'
)

print(scores)
print("Mean F1:", scores.mean())

[0.22988506 0.19277108 0.17073171 0.25581395 0.25287356]
Mean F1: 0.22041507316648995


In [136]:
# F1 Score
scores = cross_val_score(model_gbr, X, y, cv=5, scoring='f1')
print("Mean F1:", scores.mean())

# Recall (how many frauds are detected)
scores = cross_val_score(model_gbr, X, y, cv=5, scoring='recall')
print("Mean Recall:", scores.mean())

# Balanced Accuracy
scores = cross_val_score(model_gbr, X, y, cv=5, scoring='balanced_accuracy')
print("Mean Balanced Accuracy:", scores.mean())

Mean F1: 0.22041507316648995
Mean Recall: 0.1386742756804214
Mean Balanced Accuracy: 0.5683453408561913


In [138]:
import joblib

joblib.dump(model_log, 'fraud_detection_model.pkl', compress=3)

print("Model saved successfully!")

Model saved successfully!


In [139]:
loaded_model = joblib.load('fraud_detection_model.pkl')

In [140]:
import joblib

model = joblib.load("fraud_detection_model.pkl")

prediction = model.predict(X_test)